---

- include_tasks: pb1_sysupgrade_baseutils.yml

- include_tasks: pb2_install-openvpn.yml

- include_tasks: pb3_ansible.yml

#- include_tasks: pb4_install-docker.yml

- include_tasks: pb5_install-wireguard.yml
