---

- name: Install Wireguard...
  apt:
    update_cache: yes
    name:
      - wireguard
      - wireguard-tools
      - qrencode
    state: latest

- name: Copy config and keys...
  copy:
    src: templates/wireguard/
    dest: /etc/wireguard
    follow: yes

- name: Restart wireguard daemon and enabled...
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: wg-quick@wg0
