---

- name: Install Wireguard...
  apt:
    update_cache: yes
    name:
      - wireguard
      - wireguard-tools
      - qrencode
    state: latest

- name: Copy config and keys...
  copy:
    src: templates/wireguard/root/
    dest: /etc/wireguard
    follow: yes
  notify:
    - restart wireguard
